version: 1
update_configs:
  - package_manager: "python"
    directory: "/"
    update_schedule: "live"
    ignored_updates:
      - match:
          dependency_name: "pytest"
      - match:
          dependency_name: "twine"
      - match:
          dependency_name: "wheel"
      - match:
          dependency_name: "setuptools"
    automerged_updates:
      - match:
          dependency_type: "all"
          update_type: "all"
